steps:
- name: gcr.io/cloud-builders/gcloud
  args: [source, repos, clone, github_skyarvim_$PROJECT_ID, $PROJECT_ID/]
- name: gcr.io/$PROJECT_ID/composer
  dir: $PROJECT_ID/
  args: [install]
- name: gcr.io/cloud-builders/gsutil
  entrypoint: /bin/bash
  args:
  - -c
  - |
    gsutil cp gs://$PROJECT_ID.appspot.com/app.yaml $PROJECT_ID/
    gsutil cp gs://$PROJECT_ID.appspot.com/.env.$PROJECT_ID $PROJECT_ID/.env
#- name: gcr.io/cloud-builders/docker
#  args: [run, -d, -p, 127.0.0.1:3306:3306, gcr.io/cloudsql-docker/gce-proxy, /cloud_sql_proxy, -instances=$PROJECT_ID:asia-east2:$PROJECT_ID=tcp:0.0.0.0:3306]
#- name: gcr.io/cloudsql-docker/gce-proxy
#  args: [/cloud_sql_proxy, '-instances=$PROJECT_ID:asia-east2:$PROJECT_ID=tcp:3306 > cloudsql.log 2>&1 &']
#- name: gcr.io/cloud-builders/wget
#  entrypoint: /bin/bash
#  args:
#  - -c
#  - |
#    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
#    chmod +x cloud_sql_proxy
#    ./cloud_sql_proxy -dir=/cloudsql -instances=$PROJECT_ID:asia-east2:$PROJECT_ID=tcp:3306 &
- name: gcr.io/cloud-builders/wget
  entrypoint: /bin/bash
  args:
  - -c
  - |
    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O $PROJECT_ID/cloud_sql_proxy
- name: gcr.io/$PROJECT_ID/php
  entrypoint: /bin/bash
  dir: $PROJECT_ID/
  args:
  - -c
  - |
    php artisan key:generate --show --no-ansi > my_php_key
    chmod +x cloud_sql_proxy
    ./cloud_sql_proxy -instances=$PROJECT_ID:asia-east2:$PROJECT_ID=tcp:3306
    php artisan migrate
#    php artisan session:table
#- name: gcr.io/$PROJECT_ID/php
#  entrypoint: /bin/bash
#  dir: $PROJECT_ID/
#  args: [-c, php artisan key:generate --show --no-ansi > my_php_key]
#- name: gcr.io/cloud-builders/gcloud
#  entrypoint: /bin/bash
#  args:
#  - -c
#  - |
#    sed -i "s#MY_APP_KEY#$(cat $PROJECT_ID/my_php_key)#" $PROJECT_ID/app.yaml
#    gcloud app deploy $PROJECT_ID/app.yaml --stop-previous-version
timeout: 1800s
