steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args: [-c, gcloud source repos clone github_skyarvim_tnfarm tnfarm/]
- name: gcr.io/tnfarm/composer
  entrypoint: /bin/bash
  dir: tnfarm/
  args: [-c, composer install]
- name: gcr.io/cloud-builders/gsutil
  entrypoint: /bin/bash
  dir: tnfarm/
  args: [-c, gsutil cp cloudbuild/app.yaml .]
- name: gcr.io/cloud-builders/gsutil
  entrypoint: /bin/bash
  dir: tnfarm/
  args: [-c, gsutil cp cloudbuild/.gcloudignore .]
- name: gcr.io/tnfarm/php
  entrypoint: /bin/bash
  dir: tnfarm/
  args: [-c, php artisan key:generate --show --no-ansi > mykey]
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  dir: tnfarm/
  args: [-c, sed -i "s#MY_APP_KEY#$(cat mykey)#" app.yaml]
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args: [-c, gcloud app deploy tnfarm/app.yaml --stop-previous-version]
timeout: 1800s
