steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args: [-c, gcloud source repos clone github_skyarvim_$PROJECT_ID $PROJECT_ID/]
- name: gcr.io/$PROJECT_ID/composer
  entrypoint: /bin/bash
  dir: $PROJECT_ID/
  args: [-c, composer install]
- name: gcr.io/cloud-builders/gsutil
  entrypoint: /bin/bash
  args: [-c, gsutil cp gs://$PROJECT_ID.appspot.com/app.yaml $PROJECT_ID/]
- name: gcr.io/$PROJECT_ID/php
  entrypoint: /bin/bash
  dir: $PROJECT_ID/
  args: [-c, php artisan key:generate --show --no-ansi > my_php_key]
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args:
  - -c
  - |
    sed -i "s#MY_APP_KEY#$(cat $PROJECT_ID/my_php_key)#" $PROJECT_ID/app.yaml
    gcloud app deploy $PROJECT_ID/app.yaml --stop-previous-version
timeout: 1800s
